### ISSUE TITLE
qt, plasma, wayland, synology drive 3.0.2

### ISSUE THREAD

**Issue by carabao72** [flathub/com.synology.SynologyDrive#17]
bonjour

J'ai un soucis avec QT et wayland, 

`qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`

La version précédente fonctionnait bien (3.0.1)

Merci

********
hello

I have a problem with QT and wayland

`qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`

Previous version worked well (3.0.1)

Thank You
*********

Fedora 35, wayland, plasma kde (5.23.5), qt (5.15.2)

**Comment by carabao72** [comment]
unset QT_QPA_PLATFORM
bash-5.1$ flatpak run com.synology.SynologyDrive
bash-5.1$ lib path = '/app/extra/SynologyDrive/lib/plugins'
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

**Comment by carabao72** [comment]
flatpak -v run com.synology.SynologyDrive
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/michel/.local/share/flatpak
F: Opening user flatpak installation at path /home/michel/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/michel/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/xxxxxxxxxxx/files/lib32 does not exist
F: Cleaning up unused container id xxxx yyyyy
F: Cleaning up per-app-ID state for com.synology.SynologyDrive
F: Allocated instance id xxxxxxxx
F: Add defaults in dir /com/synology/SynologyDrive/
F: Add locks in dir /com/synology/SynologyDrive/
F: Allowing homedir access
F: Allowing x11 access
F: Running 'bwrap --args 37 xdg-dbus-proxy --args=39'
F: Running 'bwrap --args 37 synology-drive'
bash-5.1$ lib path = '/app/extra/SynologyDrive/lib/plugins'
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

**Comment by jeena** [comment]
I have the same problem with both flatpac and Arch AUR version, but once I use `unset QT_QPA_PLATFORM` then it works for me.

**Comment by RayJW** [comment]
I just checked, and it works fine on Wayland with Fedora 37. Could you maybe recheck and see if the new version published has fixed your issue by any chance?
