### ISSUE TITLE
Missing version 3.1.0 release 12923

### ISSUE THREAD

**Issue by jaroslavresler** [flathub/com.synology.SynologyDrive#22]
The latest version of Synology Drive Client is:
<release version="3.1.0" release="12923" date="2022-04-28"/>
Could it be possible to add it to the com.synology.SynologyDrive.metainfo.xml?
Thanks a lot.
Jaroslav

**Comment by nicolagit** [comment]
Hi.
I'm also looking for V3.1.0-r12923.

I updated the files (here in attachment) but i'm not sure how to create a Merge/Pull request in GitHub.
[com.synology.SynologyDrive.zip](https://github.com/flathub/com.synology.SynologyDrive/files/9376961/com.synology.SynologyDrive.zip)

**Comment by jibsaramnim** [comment]
Fixed with #24, thanks to @RayJW!
