### ISSUE TITLE
No system tray icon is shown

### ISSUE THREAD

**Issue by thecursedfly** [flathub/com.synology.SynologyDrive#3]
After the Synology Drive Client is installed and configured to sync with the NAS, the following option can be configured:
- Global settings > Display > Toolbar icon style > Enable: Use minimalist system tray icon

After this, a tray icon should be shown for the application whenever the main window is closed.

However, currently no icon is shown, although the application is indeed minimized to the system tray area. In fact, it is possible to guess the space where the icon should be and right click on it to get the Synology Drive context menu.

**Comment by tomkv** [comment]
For me, it shows a three dots in the systray area (on Ubuntu, with AppIndicators).

Normally, it should show full-color icon. The option that @thecursedfly writes about is a monochromatic one, that should better fit in with the Gnome panel. *Neither* of them are shown.

In a normal install from the Synology-provided deb, they work as they should.

**Comment by gregos-winus** [comment]
I am aware of this issue. Many apps have the same behaviour (eg 3 dots in the task bar) : transmission, vlc... Discord has the correct behaviour (eg icon in task bar).
But I have not yet discriminate "the little difference that makes the thing"

**Comment by HorstBaerbel** [comment]
I see no tray icon here on Fedora 35 either

**Comment by ppiutti** [comment]
This is broken again in Fedora 37 (GNOME 43) with Appindicator extension installed. Most apps icons are displayed but the Drive one is missing. It used to work in Fedora 37. Sync keeps happening on the background but tray icon is not shown. Tested in two separate installation (F36 > F37 upgrade and clean F37 install): same results.

**Comment by AmrEldib** [comment]
I have the same issue; system tray icon is missing.
I'm using Pop!_OS 22.04 LTS and GNOME 42.3.1. Tested in Wayland and X11
Appindicator extension is also installed. Other apps icons show up correctly but Drive doesn't
App is running fine and syncs correctly.

**Comment by AmrEldib** [comment]
Thank you @e1ven 
This fixed it for me on Gnome Wayland (I'll try later on X11)
I didn't get the same error when I ran it from the terminal, but the issue seems fixed by applying the command to grant permission (and confirmed in flatseal, under `Session Bus > Owns > org.kde.StatusNotifierItem-7-1` )

**Comment by ppiutti** [comment]
Thank you @e1ven I confirm your procedure works. The only annoying thing is that if I open the System Tray Menu, it does not appear below the tray icon but in the middle of the desktop. But I think I can live with it :)
