### ISSUE TITLE
steam deck,base on arch linux, unable to start， debug.message: Cannot find path by key

### ISSUE THREAD

**Issue by lisyclover** [flathub/com.synology.SynologyDrive#32]
debug.message: Cannot find path by key "user_cloud_station_app_path"
debug.message: Cannot find path by key "user_cloud_station_data_path"
debug.message: Cannot find path by key "user_cloud_station_working_dir_path"
debug.message: Cannot find path by key "user_cloud_station_drive_ui_path"

**Comment by lil5** [comment]
As steam doesn't provide out of the box ISO's I'm unable to test it

On the other hand this might be an old config file conflict;
If you can try to delete the configuration files related to synology drive.

**Comment by lil5** [comment]
https://github.com/flathub/com.synology.SynologyDrive/issues/30#issuecomment-1485859352

This might be your fix
