### ISSUE TITLE
error installing package - raspberry pi4 

### ISSUE THREAD

**Issue by bbuz2** [flathub/com.synology.SynologyDrive#4]
hello i couldnt install,

flatpak install flathub com.synology.SynologyDrive
Looking for matches…
error: Nothing matches com.synology.SynologyDrive in remote flathub

with flatpakref file:

flatpak install com.synology.SynologyDrive.flatpakref
error: No such ref 'app/com.synology.SynologyDrive/arm/stable' in remote flathub

thank you

**Comment by gregos-winus** [comment]
Synology Drive is available only on x86_64.
Flatpak is not yet capable of a miraculous port to arm or arm64.

**Comment by bbuz2** [comment]
Thank you for your email.
Regards
