### ISSUE TITLE
Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

### ISSUE THREAD

**Issue by jasongullifer** [flathub/com.synology.SynologyDrive#44]
I'm attempting to install this flatpak on a new system running Fedora 39 (flathub is enabled). I receive the error message below: 

`Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.synology.SynologyDrive: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256`

I tried on a couple different computers (Pop OS 22.04 and another Fedora 39) and received the same error.  It happens when I run  `flatpak install com.synology.SynologyDrive` or when trying to install through the graphical Gnome software center.

**Comment by ExodoPlex** [comment]
Also having this exact issue on Fedora 39 Silverblue.

Please feel free to reach to to me for any testing I can do to help.

**Comment by faeb5** [comment]
The problem seems to be this:
`ar: error while loading shared libraries: libbfd-2.41.so: cannot open shared object file: No such file or directory`

I saw a similar error in other flatpaks. One solution was to switch from `ar` to `bsdtar` which should be included in the runtime. Could this help here, too?

**Comment by jasongullifer** [comment]
I was playing around `flatpak-builder` from inside a distrobox container (I'm also on silverblue). Changing the  line calling `ar` inside the yaml file to `bsdtar -xf synology-drive.deb` does appear to give a successful build. 

However, I can't confirm that the build works. I can't yet figure out how to successfully run the flatpak from inside distrobox, nor could I figure out how to install from the build-dir outside the box.

As a workaround until the flatpak is fixed, I was able to create a debian distrobox container, install some graphical and net-tool dependencies, then install synology-drive from the deb file with `dpkg`. I can now open drive from inside the debian container; it stays running until the next reboot.

**Comment by jasongullifer** [comment]
I tested the most recent build and can confirm what @feab5 said about the lack of try icons. Also for me, on opening the application once, it appears not to run (no syncing occurs). If I open again, I am presented with the synology-drive system menu, and syncing works, but I have no icon in my gnome AppIndicator panel.

**Comment by AmrEldib** [comment]
Is there a fix or workaround for this issue?
I tried installing the [test build](https://github.com/flathub/com.synology.SynologyDrive/pull/45#issuecomment-1936598196), but I get a 404 error
I'm still unable to install the Drive package on Fedora 39
Thank you!

**Comment by lil5** [comment]
This should soon be resolved with the next build, let me know!

**Comment by AmrEldib** [comment]
This resolved it. I can install it now on Fedora 39. Thank you very much!

**Comment by lil5** [comment]
Great! @AmrEldib Thanks for the response!
