### ISSUE TITLE
Update --> Version: 3.0.0-12663

### ISSUE THREAD

**Issue by carabao72** [flathub/com.synology.SynologyDrive#7]
Hello,

Would it be possible to offer version 3.x of this utility to work under DSM 7.0,  ?

Thanks  you.

changelog: https://www.synology.com/fr-fr/releaseNote/SynologyDriveClient

**Comment by kevinsmia1939** [comment]
I create PR here: https://github.com/flathub/com.synology.SynologyDrive/pull/8

**Comment by hfiguiere** [comment]
it should appear in a few hours

**Comment by carabao72** [comment]
hello, 

Thank you for this 3.x version of the utility..

I checked in the settings of the application minimalist icon (I’m not sure of the term anymore) and there is a bug with the couple wayland/ kde, the icon does not appear in the taskbar of kde.

How to undo this change, I can’t find the configuration file in the application directory.

Thank you
