### ISSUE TITLE
Bug: App not shown in 'AppIndicator KStatusNotifierItem Support' GNOME extension

### ISSUE THREAD

**Issue by mferus** [flathub/com.synology.SynologyDrive#9]
System: fedora 34 with newest packages

Trace from console:

[xyz@xyz ~]$ flatpak run com.synology.SynologyDrive
[xyz@xyz ~]$ lib path = '/app/extra/SynologyDrive/lib/plugins'
Qt: Session management error: None of the authentication protocols specified are supported
Gtk-Message: 10:46:30.103: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:46:30.104: Failed to load module "pk-gtk-module"
Gtk-Message: 10:46:30.104: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:46:30.104: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
failed to register service "org.kde.StatusNotifierItem-7-1"
QLayout: Attempting to add QLayout "" to TutorialPanel "tutorial_panel", which already has a layout
QLayout: Attempting to add QLayout "" to TutorialPanel "tutorial_panel", which already has a layout
QLayout: Attempting to add QLayout "" to TutorialPanel "tutorial_panel", which already has a layout
QLayout: Attempting to add QLayout "" to TutorialPanel "tutorial_panel", which already has a layout
QLayout: Attempting to add QLayout "" to TutorialDiagram "", which already has a layout
QLayout: Attempting to add QLayout "" to TutorialDiagram "", which already has a layout
sh: linia 1: /sbin/udevadm: Nie ma takiego pliku ani katalogu // no folder or file found
sh: linia 1: /sbin/ifconfig: Nie ma takiego pliku ani katalogu // no folder or file found

**Comment by kevinsmia1939** [comment]
Did you mean that system tray icon does not appear?
Try run this command, let me know.
`flatpak run --socket=session-bus com.synology.SynologyDrive`

**Comment by mferus** [comment]
_Did you mean that system tray icon does not appear?_

Correct.

 _Try run this command, let me know._

It works, also proper icon shows up.

**Comment by kevinsmia1939** [comment]
> _Did you mean that system tray icon does not appear?_
> 
> Correct.
> 
> _Try run this command, let me know._
> 
> It works, also proper icon shows up.

it should be fixed now

**Comment by mferus** [comment]
It does work, thank you for help!
